repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args: ["--no-update"]
    -   name: requirements.txt
        id: poetry-export
    -   name: requirements-dev.txt
        id: poetry-export
        args: ["--only", "dev", "-o", "requirements-dev.txt"]
