repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
    -   id: poetry-check
        args: ["--lock"]
    -   name: Export requirements.txt
        id: poetry-export
    -   name: Export requirements-dev.txt
        id: poetry-export
        args: ["--only", "dev", "-o", "requirements-dev.txt"]
